# ABOUTME: Provisioning tool — issues a unique nkey per device/service and renders the NATS auth config.
# ABOUTME: CRA secure-by-default: no shared/default credential, and every identity gets least-privilege subjects.

import argparse
import json
import os

import nkey
import tls_certs

# Container paths the secure overlay mounts the TLS chain at (see docker-compose.secure.yml).
TLS_CERT_PATH = "/etc/nats/tls/server-cert.pem"
TLS_KEY_PATH = "/etc/nats/tls/server-key.pem"
# SANs the server cert must carry so clients verify it on both the compose network and the host.
TLS_HOSTNAMES = ["nats", "localhost", "127.0.0.1"]

# Per-role subject permissions. Devices are scoped to their OWN subject; a board cannot
# publish as another container or reach the control/JetStream planes. Services get exactly
# the subjects their code uses (confirmed against bridge/main.py, vector.yaml, fakegen, publish_artifact).
ROLE_TEMPLATES = {
    # A device publishes only its own telemetry (+ its own operator-gated Contract E capture sink)
    # and listens only for its own model rollouts, control, and Contract E capture commands.
    "device": lambda line, cid: {
        "publish": [f"edge.{line}.{cid}", f"capture.{line}.{cid}.data"],
        "subscribe": [f"models.{line}.deploy", f"models.{line}.artifact", f"control.{line}",
                      f"capture.{line}.{cid}.cmd"],
    },
    # Vector boundary gateway: consume the whole device plane, forward only inference.
    "vector": lambda line, cid: {
        "publish": ["inference.>"],
        "subscribe": ["edge.>"],
    },
    # Bridge owns the cloud side and drives JetStream, so it needs the JS API + inbox.
    "bridge": lambda line, cid: {
        # Drives JetStream: API calls + per-message acks ($JS.ACK.>), delivered on its inbox.
        "publish": ["labels.>", "models.>", "control.>", "$JS.API.>", "$JS.ACK.>"],
        "subscribe": ["inference.>", "labels.>", "models.>", "_INBOX.>", "$JS.API.>"],
    },
    # Synthetic device-plane publisher (dev only) — same data plane as a real board.
    "fakegen": lambda line, cid: {
        "publish": [f"edge.{line}.>"],
        "subscribe": [f"control.{line}"],
    },
    # Model-pipeline gateway streams artifact bytes to devices.
    "pipeline": lambda line, cid: {
        "publish": ["models.>"],
        "subscribe": [],
    },
}


def permissions_for(role: str, line: str, cid: str) -> dict:
    """Resolve the least-privilege publish/subscribe allow-lists for one identity. Pure."""
    if role not in ROLE_TEMPLATES:
        raise ValueError(f"unknown role {role!r}; known: {sorted(ROLE_TEMPLATES)}")
    return ROLE_TEMPLATES[role](line, cid)


def build_identities(fleet: dict) -> list[dict]:
    """Expand a fleet inventory into identities with a fresh, unique nkey each. Returns issuance records."""
    identities = []
    for dev in fleet.get("devices", []):
        seed, public = nkey.create_user()
        identities.append({
            "name": dev["id"], "role": "device", "line": dev["line"],
            "seed": seed, "public": public,
            "permissions": permissions_for("device", dev["line"], dev["id"]),
        })
    for svc in fleet.get("services", []):
        seed, public = nkey.create_user()
        line = svc.get("line", "*")
        identities.append({
            "name": svc["id"], "role": svc["role"], "line": line,
            "seed": seed, "public": public,
            "permissions": permissions_for(svc["role"], line, svc["id"]),
        })
    return identities


def _subject_list(subjects: list[str]) -> str:
    return "[" + ", ".join(f'"{s}"' for s in subjects) + "]"


def render_server_config(identities: list[dict], tls: bool = False) -> str:
    """Render a nats-server.conf authorization block from issued identities. Pure — public keys only, no secrets.

    With tls=True, add a server-auth TLS block (clients verify the server cert; client identity is the
    nkey, so no client cert is required). The cert/key are mounted at the TLS_*_PATH container paths.
    """
    lines = [
        "# ABOUTME: Generated NATS server config — per-identity nkey auth with least-privilege subjects.",
        "# ABOUTME: Generated by provision.py from fleet.json; do not edit by hand. Contains public keys only.",
        "",
        "port: 4222",
        "http_port: 8222",
        "jetstream {}",
        "",
    ]
    if tls:
        lines += [
            "# TLS: encrypt the fabric (CRA confidentiality/integrity in transit). Server-auth only —",
            "# clients verify this cert against the CA; their identity is the nkey, not a client cert.",
            "tls {",
            f'  cert_file: "{TLS_CERT_PATH}"',
            f'  key_file: "{TLS_KEY_PATH}"',
            "}",
            "",
        ]
    lines += [
        "# No anonymous fallback and no default password: an unknown or anonymous client is rejected.",
        "authorization {",
        "  users = [",
    ]
    for ident in identities:
        perms = ident["permissions"]
        lines.append(f'    # {ident["name"]} ({ident["role"]})')
        lines.append("    {")
        lines.append(f'      nkey: "{ident["public"]}"')
        lines.append("      permissions {")
        lines.append(f'        publish = {{ allow = {_subject_list(perms["publish"])} }}')
        lines.append(f'        subscribe = {{ allow = {_subject_list(perms["subscribe"])} }}')
        lines.append("      }")
        lines.append("    }")
    lines.append("  ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_artifacts(identities: list[dict], out_dir: str) -> None:
    """Write per-identity seed files (0600) and the rendered server config."""
    creds_dir = os.path.join(out_dir, "creds")
    os.makedirs(creds_dir, exist_ok=True)
    for ident in identities:
        path = os.path.join(creds_dir, f"{ident['name']}.nk")
        # 0600 the seed: it is the secret that would live in the board's protected storage.
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as f:
            # No trailing newline: nats-py reads the exact file bytes, so a stray \n corrupts the seed.
            f.write(ident["seed"])
        # The public nkey is not secret; some clients (e.g. Vector) need it alongside the seed.
        with open(path + ".pub", "w") as f:
            f.write(ident["public"] + "\n")

    # TLS chain: a fresh CA + server cert each run. ca.pem is public (clients trust it); the
    # server key is secret (0600). The CA private key is intentionally not persisted — re-running
    # provision re-mints the chain rather than leaving a fleet-wide signing key on disk.
    tls_dir = os.path.join(out_dir, "tls")
    os.makedirs(tls_dir, exist_ok=True)
    ca_pem, ca_key_pem = tls_certs.generate_ca()
    srv_pem, srv_key_pem = tls_certs.generate_server_cert(ca_pem, ca_key_pem, TLS_HOSTNAMES)
    with open(os.path.join(tls_dir, "ca.pem"), "wb") as f:
        f.write(ca_pem)
    with open(os.path.join(tls_dir, "server-cert.pem"), "wb") as f:
        f.write(srv_pem)
    fd = os.open(os.path.join(tls_dir, "server-key.pem"), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(srv_key_pem)

    with open(os.path.join(out_dir, "nats-server.conf"), "w") as f:
        f.write(render_server_config(identities, tls=True))


def main() -> int:
    ap = argparse.ArgumentParser(description="Issue per-identity nkeys and render the NATS auth config.")
    ap.add_argument("--fleet", default="pipeline/fleet.json", help="fleet inventory JSON")
    ap.add_argument("--out", default="nats", help="output dir for nats-server.conf + creds/")
    args = ap.parse_args()

    with open(args.fleet) as f:
        fleet = json.load(f)

    identities = build_identities(fleet)
    write_artifacts(identities, args.out)

    print(f"provisioned {len(identities)} unique identities -> {args.out}/")
    for ident in identities:
        print(f"  {ident['name']:<10} {ident['role']:<9} {ident['public'][:12]}…  creds/{ident['name']}.nk")
    print(f"server config: {args.out}/nats-server.conf")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
